FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force

RUN npm install --legacy-peer-deps

COPY . .
# COPY entrypoint.sh /app/

# CMD ["./entrypoint.sh"] # Use the entrypoint script

# prisma generate and populate the database
RUN npx prisma generate


EXPOSE 3000

CMD [  "npm", "start","dev", "start:migrate:prod", "npm","run","migrate"] 