FROM node:20.11.1-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY lock/.htaccess ./lock/.htaccess
COPY lock/.htpasswd ./lock/.htpasswd
COPY package*.json ./


# Install dependencies
RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Generate Prisma Client code
RUN npx prisma generate
RUN npx run migrate


CMD [ "npx", "prisma", "studio", "--port", "5558" ]

