name: Build and Deploy NestJS App

# Déclencheur : Exécuter ce workflow à chaque push sur la branche 'main'
on:
  push:
    branches: [main] # Adaptez si votre branche principale a un autre nom (ex: master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Utiliser un runner Linux standard

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4 # Utilise l'action standard de checkout

      # 2. Configurer Docker Buildx (pour de meilleures capacités de build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Utilise le secret DOCKERHUB_TOKEN

      # 4. Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Le contexte de build est la racine du dépôt
          dockerfile: Dockerfile.nest # Spécifiez le nom de votre Dockerfile NestJS
          push: true # Pousser l'image après le build
          tags: | # Les tags de l'image
            lorainep/cityzen-back:latest 
            lorainep/cityzen-back:${{ github.sha }}
          cache-from: type=gha # Activer le cache de build GitHub Actions
          cache-to: type=gha,mode=max

      # 5. Déclencher le webhook de déploiement Portainer
      - name: Trigger Portainer Deploy Webhook
        run: curl -s -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }} # Appel simple au webhook via curl
