name: Build and Deploy NestJS App
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Utilise environnement Ubuntu dans GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lorainep/citydo-back:latest 
            lorainep/citydo-back:${{ github.sha }}
          cache-from: type=gha # Activer le cache de build GitHub Actions
          cache-to: type=gha,mode=max

      - name: Trigger Portainer Deploy Webhook
        # Appel simple au webhook via curl (configuré au niveau de Portainer)
        run: curl -s -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
